AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Resources:
  AdventOfCodeApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: 'api-spec.yaml'

  AdventOfCodeApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../dist/src
      Handler: handler.handler
      Runtime: nodejs18.x
      Events:
         ApiEvent:
           Type: Api
           Properties:
             Path: /{year}/{day}
             Method: post
             RestApiId:
               Ref: AdventOfCodeApi
